plugins {
    id "dev.architectury.loom" version "1.2-SNAPSHOT"
    id 'maven-publish'
    id "com.matthewprenger.cursegradle" version "1.4.0"
}

sourceCompatibility = targetCompatibility = compileJava.sourceCompatibility = compileJava.targetCompatibility = 17

def ENV = System.getenv()
version = "${minecraft_version}-${mod_version}-build.${ENV.GITHUB_RUN_NUMBER ?: 9999}"
group= "pro.mikey"
archivesBaseName = "advanced-xray-forge"

loom {
    silentMojangMappingsLicense()

    forge {
        mixinConfigs = [
                "xray.mixins.json"
        ]
    }

    accessWidenerPath = file("src/main/resources/xray.accesswidener")
}

repositories {
    maven {
        url "https://maven.neoforged.net/releases"
    }
    maven {
        url "https://api.modrinth.com/maven"
        content {
            includeGroup "maven.modrinth"
        }
    }
    maven {
        url "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
}

def replaceProperties = [
    minecraft_version: minecraft_version,
    minecraft_version_range: minecraft_version_range.replace("[%base]", minecraft_version),
    forge_version_range: forge_version.split("\\.").first(),
    version: version,
]

processResources {
    inputs.properties replaceProperties
    replaceProperties.put 'project', project

    filesMatching("META-INF/mods.toml") {
        expand replaceProperties
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()

    forge "net.neoforged:forge:${project.minecraft_version}-${project.forge_version}"

    modImplementation "maven.modrinth:lootr:0.7.35.94"

    // Prerequisites
    modImplementation "curse.maven:framework-549225:7573740"          // Framework (for Furniture Refurbished)
    modImplementation "curse.maven:geckolib-388172:7553267"           // GeckoLib (for Zombie Extreme)
    modImplementation "maven.modrinth:curios:5.14.1+1.20.1"          // Curios API (for Apocalypse Now)

    // MrCrayfish's Furniture Mod: Refurbished
    modImplementation "curse.maven:refurbished-furniture-897116:7110922"

    // Doomsday Decoration
    modImplementation "curse.maven:doomsday-decoration-1180487:6781856"

    // Zombie Extreme
    modImplementation "curse.maven:zombie-extreme-392809:7014500"

    // Apocalypse Now
    modImplementation "maven.modrinth:apocalypse-now:3.0.5"
}

repositories {
    maven {
        url "https://maven.saps.dev/mirror"
    }
}

compileJava {
    options.encoding = "UTF-8"
}

java {
    withSourcesJar()
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.archivesBaseName}" }
    }

    manifest {
        attributes([
                "Specification-Title"     : "Advanced XRay",
                "Specification-Vendor"    : "Advanced XRay",
                "Specification-Version"   : "1",
                "Implementation-Title"    : "Advanced XRay",
                "Implementation-Version"  : version,
                "Implementation-Vendor"   : "Advanced XRay",
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = rootProject.archivesBaseName
            from components.java
        }
    }

    repositories {
        if (ENV.SAPS_TOKEN) {
            maven {
                url "https://maven.saps.dev/releases"
                credentials {
                    username = "mikeymods"
                    password = "${ENV.SAPS_TOKEN}"
                }
            }
        }
    }
}

if (ENV.CURSE_DEPLOY_TOKEN) {
    curseforge {
        apiKey = ENV.CURSE_DEPLOY_TOKEN
        project {
            id = project.curse_id
            releaseType = "release"
            addGameVersion "Forge"
            addGameVersion "$minecraft_version"
            changelog = file("./CHANGELOG.md")
            changelogType = 'markdown'
            mainArtifact(remapJar)
        }
    }
}
